- hosts: all
  gather_facts: false
  sudo: yes
  tasks:
    - name: ensure apt key is installed
      #$ sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
      apt_key: id=58118E89F3A912897C070ADBF76221572C52609D keyserver=hkp://p80.pool.sks-keyservers.net:80 state=present
      
    - name: ensure has docker apt source
      apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-trusty main' state=present
    - name: ensure old docker is removed
      apt: name=lxc-docker state=absent
      
    - name: ensure docker is installed
      apt: name=docker-engine state=present
      
    - name: ensure group docker exists
      group: name=docker state=present
      
    - name: ensure I am in docker group
      user: name=ezhuwya groups=docker append=yes
